[EAGLE-3089]
Clarifai/clarifai-python-utils pull request #47
Opened 2023-05-24 09:10 UTC by steph-en-m

- [ ] Reduce unnecessary dir nesting to improve project structure
- [ ] Add model api utils

2023-05-30 22:02 UTC, yangshengBE commented on clarifai/models/api.py
> +class Auth:
I am not sure if we really need this Auth class (other scripts seems creating a class with these info). Even if, it seems like auth will be the leaf of the dependency tree,  api and clients will import it?

2023-05-31 07:52 UTC, steph-en-m commented on clarifai/models/api.py
> +class Auth:
>...(other scripts seems creating a class with these info).

Yes this is the repetition I want us to avoid going forward and enforce an "authenticate once, use everywhere" mechanism. The current data upload for instance requires a user to provide auth details (I didn't have a better solution at the time) and if we are to build other utils following the same pattern then I think it'd be inefficient and annoying to users to always require them to provide auth details.
- Using classes will also require users to create new instances each time they want to pass a new auth argument compared to using a dataclass that allows users to only update a single argument while preserving the previously passed args.
I do agree though that Auth shouldn't be in the api module. I'll explore moving it to the client package

2023-06-02 18:55 UTC, ackizilkale commented
I am fine with auth module being removed, so eventually we can use client. But I know @zeiler has some ideas around authentication. Let's make sure he is ok with this change.

2023-06-02 18:57 UTC, steph-en-m commented
yeah sure. I believe there are still ways to make auth better.

2023-06-02 19:03 UTC, zeiler commented
i think this will break all our UI modules. 

Why not just add to clarifai/auth/__init__.py like some imports of the helper class like 
```
from clarifai.auth.helper import ClarifaiAuthHelper as Auth
```
if you want to make importing look like 
```
from clarifai.auth import ClarifaiAuthHelp
```
then it's backwards compatible and a simpler change.

2023-06-02 19:04 UTC, zeiler commented
i'd rather keep the folders because there is likely going to be lots of stuff in each folder as this client grows rapidly now.

2023-06-02 19:05 UTC, zeiler commented on clarifai/models/api.py
> +def list_model_types(auth: Type[Auth]) -> Tuple[Dict, Dict, Dict]:
why wouldn't this be in the listing folder like all the other types of resources? then it would be consistent.

2023-06-02 19:06 UTC, zeiler requested changes

2023-06-02 19:06 UTC, zeiler commented on clarifai/models/api.py
> +def post_model(auth: Type[Auth]):
i picture we're going to want to add class methods on a nice object in the near future like Model.post() or something like that.

2023-06-02 19:10 UTC, steph-en-m commented on clarifai/models/api.py
> +def list_model_types(auth: Type[Auth]) -> Tuple[Dict, Dict, Dict]:
>i'd rather keep the folders because there is likely going to be lots of stuff in each folder as this client grows rapidly now.

I believe as more utils are added in the future, it'd be a better design pattern to have the them packaged under their respective core services such as models, datasets, workflows, etc, which would encourage easier import patterns/improve usability.

2023-06-02 19:19 UTC, steph-en-m commented on clarifai/models/api.py
> +def post_model(auth: Type[Auth]):
Had avoided thatso that users don't have to do any object initialization apart from when authentication but can revert to this if it's the preferred one

2023-06-02 20:21 UTC, yangshengBE commented on clarifai/models/api.py
> +def post_model(auth: Type[Auth]):
DevX team will redesign our SDK and that would including wrapping into a class object.

2023-06-03 19:24 UTC, ackizilkale approved these changes
lgtm

2023-06-05 03:16 UTC, zeiler commented on clarifai/client/auth_handler.py
> +# Copyright 2023 Clarifai, Inc.
i'm still confused why we need this class when we already have the auth helper?

2023-06-05 05:51 UTC, steph-en-m commented on clarifai/client/auth_handler.py
> +# Copyright 2023 Clarifai, Inc.
auth helper requires users to set auth credentials as environment variables, this eases their work by doing that for them. I didn't want to modify the auth helper as I assumed that's the preferred design choice.

2023-06-05 13:25 UTC, zeiler commented on clarifai/client/auth_handler.py
> +# Copyright 2023 Clarifai, Inc.
no it doesn't https://github.com/Clarifai/clarifai-python-utils/blob/main/clarifai/auth/helper.py#L56 it's __init__() already does exactly what your new class does. It also has conventience classmethods to construct it from env variables and streamlit and other places we can add in the future.

2023-06-05 13:37 UTC, steph-en-m commented on clarifai/client/auth_handler.py
> +# Copyright 2023 Clarifai, Inc.
The client package by default calls .from_env() to read user credentials and these env vars aren't set anywhere in the init() or the from_env method here https://github.com/Clarifai/clarifai-python-utils/blob/main/clarifai/auth/helper.py#L194

2023-06-05 14:16 UTC, zeiler commented on clarifai/client/auth_handler.py
> +# Copyright 2023 Clarifai, Inc.
where is it required?

2023-06-05 14:19 UTC, steph-en-m commented on clarifai/client/auth_handler.py
> +# Copyright 2023 Clarifai, Inc.
I meant it's best to use that method of auth not the web based methods

2023-06-05 14:31 UTC, steph-en-m commented on clarifai/client/auth_handler.py
> +# Copyright 2023 Clarifai, Inc.
The only thing this auth class is doing is setting user credentials as env vars so they can be read by .from_env() without users having to manually export them as env vars. This isn't done by ClarifaiAuthHelper init() or from_env()

2023-06-05 14:48 UTC, zeiler commented on clarifai/client/auth_handler.py
> +# Copyright 2023 Clarifai, Inc.
you should never need to do this or do it in general since ClarifaiAuthHelper init() doesn't need the env variables set.

2023-06-05 14:52 UTC, steph-en-m commented on clarifai/client/auth_handler.py
> +# Copyright 2023 Clarifai, Inc.
I think data_upload can give better context of why we use the from_env().
setting the env vars for users is more of a user-friendliness feature.

2023-06-05 17:09 UTC, steph-en-m commented on clarifai/client/auth_handler.py
> +# Copyright 2023 Clarifai, Inc.
Okay, I think I see what your point was now. Just passed the ClarifaiAuthHelper instance object to create_stub() and it did the same thing.

2023-06-07 17:12 UTC, zeiler approved these changes
I think this is ok for now. I do think this will likely evolve quite a bit as the overall rearchitecture of the client happens but we shouldn't block upload for now.

2023-06-07 17:14 UTC, merged