EAGLE-3186
Clarifai/clarifai-python-utils pull request #65
Opened 2023-06-29 13:30 UTC by phatvo9

Adding cli to upload the zipped model

2023-06-29 16:43 UTC, HarmitMinhas96 commented on clarifai/models/model_serving/cli/deploy_cli.py
> +]
We also define these here: clarifai_utils/models/model_serving/cli/repository.py
Can we reorg them to be in one common spot?

2023-06-29 16:43 UTC, HarmitMinhas96 commented on clarifai/models/model_serving/cli/deploy_cli.py
> +      help="Short desccription of model")
description**

2023-06-29 16:43 UTC, HarmitMinhas96 commented on clarifai/models/model_serving/cli/deploy_cli.py
> +  parser.add_argument(
description**

2023-06-29 16:43 UTC, HarmitMinhas96 commented on clarifai/models/model_serving/cli/deploy_cli.py
> +  resp = model_api.post_model(
This does only post models, but this behavior is deprecated and will be removed soon. We need to do:
PostModels -- which should have model id and model type, and potentially a description
PostModelVersions -- which contains all the model version information (everything else in the current request)

2023-06-29 16:43 UTC, HarmitMinhas96 commented on clarifai/models/model_serving/cli/deploy_cli.py
> +    model_type = zip_filename.split('_')[-1]
Maybe comment on this relying on the user using the recommended naming convention in https://github.com/Clarifai/clarifai-python-utils/blob/6b90f1793be1277ce4d13f3411e9f5d9e8b54c89/clarifai/models/model_serving/cli/model_zip.py#L54

Also, if the user puts '_' in the model_name, this wouldn't work as expected.

2023-06-29 16:43 UTC, HarmitMinhas96 commented on clarifai/models/model_serving/model_config/deploy.py
> +      self.output_fields_map = ["concepts", "softmax_predictions"]
Why make these lists and then later convert them to dictionaries in `_parse_fields_map` ? Can't we just make them dictionaries to begin with?

2023-06-30 05:07 UTC, phatvo9 commented on clarifai/models/model_serving/model_config/deploy.py
> +      self.output_fields_map = ["concepts", "softmax_predictions"]
Right, it looks redundant. If change is required, can you recommend the best way to fix it? Revert the API PR or open new ticket for it?

2023-06-30 05:17 UTC, phatvo9 commented on clarifai/models/model_serving/cli/deploy_cli.py
> +    model_type = zip_filename.split('_')[-1]
fixed by parsing the last '_'

2023-06-30 06:23 UTC, phatvo9 commented on clarifai/models/model_serving/cli/deploy_cli.py
> +]
I always believe that we should define model types as constant variable somewhere in the module since the type repeats many times. However, it is not defined anywhere, I have to make it myself. Is it good to reorg within this pr?

2023-06-30 13:50 UTC, HarmitMinhas96 commented on clarifai/models/model_serving/cli/deploy_cli.py
> +]
I think so. It would just be adding one new file for constants, that'd get imported by the two files that currently use it?

2023-07-03 13:32 UTC, phatvo9 commented on clarifai/models/model_serving/cli/deploy_cli.py
> +    model_type = _parse_name(zip_filename)[-1]
sometimes user may need to change the model id that's why this if statement exists

2023-07-03 14:01 UTC, phatvo9 commented on clarifai/models/model_serving/cli/deploy_cli.py
> +]
model_types was moved to constants

2023-07-03 14:50 UTC, phatvo9 commented on clarifai/models/model_serving/model_config/deploy.py
> +      self.output_fields_map = ["concepts", "softmax_predictions"]
will do in https://clarifai.atlassian.net/browse/EAGLE-3241

2023-07-03 14:53 UTC, ackizilkale submitted a review, later dismissed
looks good to me.

2023-07-03 15:02 UTC, HarmitMinhas96 commented on clarifai/models/model_serving/cli/deploy_cli.py
> +]
I see, though repository.py wasn't updated to use it?

2023-07-04 10:25 UTC, phatvo9 commented on clarifai/models/model_serving/cli/deploy_cli.py
> +]
it should be there now

2023-07-04 12:11 UTC, steph-en-m requested changes

2023-07-04 12:11 UTC, steph-en-m commented on clarifai/models/model_serving/cli/deploy_cli.py
> +  deploy(model_url=args.url, model_id=args.model_id, desc=args.desc, model_type=args.model_type)
wrap the code below under one function which you can call here instead: then register the function name under the console_scripts entrypoint in setup.py as "clarifai-upload-model = clarifai.models.model_serving.cli.deploy_cli:<your-function-name-e.g.main>" so it's accessible via cli post install

2023-07-04 12:15 UTC, steph-en-m commented on clarifai/models/model_serving/cli/deploy_cli.py
> +  deploy(model_url=args.url, model_id=args.model_id, desc=args.desc, model_type=args.model_type)
Update [bullet point 7 in this README too](https://github.com/Clarifai/clarifai-python-utils/blob/EAGLE-3186/clarifai/models/model_serving/README.md#quickstart-guide-build-a-deployment-ready-model) to highlight usage

2023-07-04 13:29 UTC, phatvo9 commented on clarifai/models/model_serving/cli/deploy_cli.py
> +  deploy(model_url=args.url, model_id=args.model_id, desc=args.desc, model_type=args.model_type)
I updated following your comments

2023-07-04 15:06 UTC, steph-en-m approved these changes
LGTM!

2023-07-05 05:54 UTC, ackizilkale approved these changes
Lgtm.

2023-07-05 13:48 UTC, HarmitMinhas96 commented on clarifai/models/model_serving/cli/repository.py
I could've sworn I left a comment about this file not being updated, but now I don't see it on github 😅 
Welp, good catch updating it anyways!

2023-07-05 13:56 UTC, merged